[package]
name = "rash_core"
version = "0.1.0"
description = "Declarative shell scripting using Rust native bindings"
authors = ["Pando85 <pando855@gmail.com>"]
edition = "2018"
license-file = "../LICENSE"
homepage = "https://github.com/rash-sh/rash"
repository = "https://github.com/rash-sh/rash"
readme = "../README.md"

[lib]
name = "rash_core"
path = "src/lib.rs"

[[bin]]
name = "rash"
path = "src/main.rs"

[dependencies]
rash_derive = { path = "../rash_derive", version = "0.1.0" }
clap = "3.0.0-beta.1"
exec = "0.3.1"
fern = { version = "0.6", features = ["colored"] }
lazy_static = "1.4.0"
libc = { version = "0.2", features = ["std"] }
log = "0.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_yaml = "0.8"
tera = { version = "1", default-features = false }
term_size = "1.0.0-beta1"
yaml-rust = "0.4"

[dev-dependencies]
tempfile = "3"

[dev-dependencies.cargo-husky]
version = "1"
default-features = false # Disable features which are enabled by default
features = ["precommit-hook", "run-cargo-fmt", "run-cargo-clippy"]
