[package]
name = "rash_core"
description = "Declarative shell scripting using Rust native bindings"
version.workspace = true
authors.workspace = true
rust-version.workspace = true
edition.workspace = true
license-file.workspace = true
homepage.workspace = true
repository.workspace = true

[lib]
name = "rash_core"
path = "src/lib.rs"

[[bin]]
name = "rash"
path = "src/bin/rash.rs"

[features]
docs = ["rash_derive/docs", "schemars"]

[dependencies]
rash_derive = { path = "../rash_derive", version = "1.10.0" }
lazy_static.workspace = true
log.workspace = true
regex.workspace = true
schemars = { workspace = true, optional = true }
serde_json.workspace = true
serde_yaml.workspace = true
byte-unit = "4.0"
console = "0.15.7"
clap = { workspace = true, features = ["std", "color", "derive", "cargo"]}
exec = "0.3.1"
fern = { version = "0.6", features = ["colored"] }
ignore = "0.4"
# memfd could be added but brakes compatibility with kernels < 3.17
# ipc-channel = { version = "0.17", features = ["memfd"] }
ipc-channel = "0.17"
itertools = "0.11"
nix = { version = "0.27", features =  ["process", "user"] }
serde = { version = "1.0", features = ["derive"] }
serde-error = "0.1"
serde_with = "3.3"
shlex = "1.3"
similar = { version = "2.2", features = ["inline"] }
strum = "0.25"
strum_macros = "0.25"
tempfile = "3"
tera = { version = "1", default-features = false }
term_size = "1.0.0-beta.2"

[dev-dependencies]
criterion = "0.5"

[[bench]]
name = "docopt"
harness = false

[dev-dependencies.cargo-husky]
version = "1"
default-features = false # Disable features which are enabled by default
features = ["user-hooks"]
