[package]
name = "rash_core"
version = "1.3.1"
description = "Declarative shell scripting using Rust native bindings"
authors = ["Pando85 <pando855@gmail.com>"]
edition = "2021"
license-file = "../LICENSE"
homepage = "https://rash.sh"
repository = "https://github.com/rash-sh/rash"
readme = "../README.md"

[lib]
name = "rash_core"
path = "src/lib.rs"

[[bin]]
name = "rash"
path = "src/bin/rash.rs"

[features]
docs = ["rash_derive/docs", "schemars"]

[dependencies]
rash_derive = { path = "../rash_derive" }
byte-unit = "4.0"
console = "0.14.0"
clap = { version = "3.0.0-rc.1", features = ["std", "color", "derive", "cargo"]}
exec = "0.3.1"
fern = { version = "0.6", features = ["colored"] }
lazy_static = "1.4.0"
libc = { version = "0.2", features = ["std"] }
log = "0.4"
ignore = "0.4"
serde = { version = "1.0", features = ["derive"] }
serde_with = "1.11"
serde_json = "1.0"
serde_yaml = "0.8"
similar = { version = "2.1", features = ["inline"] }
strum = "0.23"
strum_macros = "0.23"
tempfile = "3"
tera = { version = "1", default-features = false }
term_size = "1.0.0-beta.2"
yaml-rust = "0.4"
schemars = { version = "0.8", optional = true }

[dev-dependencies.cargo-husky]
version = "1"
default-features = false # Disable features which are enabled by default
features = ["user-hooks"]
