[package]
name = "rash_core"
description = "Declarative shell scripting using Rust native bindings"
version.workspace = true
authors.workspace = true
rust-version.workspace = true
edition.workspace = true
license-file.workspace = true
homepage.workspace = true
repository.workspace = true

[lib]
name = "rash_core"
path = "src/lib.rs"

[[bin]]
name = "rash"
path = "src/bin/rash.rs"

[features]
docs = ["rash_derive/docs", "schemars"]

[dependencies]
rash_derive = { path = "../rash_derive" }
lazy_static.workspace = true
log.workspace = true
regex.workspace = true
schemars = { workspace = true, optional = true }
serde_json.workspace = true
serde_yaml.workspace = true
byte-unit = "4.0"
console = "0.15.0"
clap = { workspace = true, features = ["std", "color", "derive", "cargo"]}
exec = "0.3.1"
fern = { version = "0.6", features = ["colored"] }
ignore = "0.4"
# when memfd don't require nightly we coulld add it
# ipc-channel = { version = "0.15", features = ["memfd"] }
ipc-channel = "0.16"
itertools = "0.10"
nix = "0.24"
serde = { version = "1.0", features = ["derive"] }
serde-error = "0.1"
serde_with = "1.11"
similar = { version = "2.1", features = ["inline"] }
strum = "0.23"
strum_macros = "0.23"
tempfile = "3"
tera = { version = "1", default-features = false }
term_size = "1.0.0-beta.2"
users = "0.11"

[dev-dependencies.cargo-husky]
version = "1"
default-features = false # Disable features which are enabled by default
features = ["user-hooks"]
