[book]
authors = ["Pando85 <pando855@gmail.com>"]
language = "en"
multilingual = false
src = "src"
title = "Rash book"

[build]
build-dir = "rash-sh.github.io/docs/rash/master"

[preprocessor.rash]

[output.markdown]
