[package]
name = "mdbook_rash"
version = "1.1.0"
description = "Binary to create doc from `rash` code"
authors = ["Pando85 <pando855@gmail.com>"]
edition = "2018"
license-file = "../LICENSE"
homepage = "https://rash.sh"
repository = "https://github.com/pando85/rash"
readme = "../README.md"

[[bin]]
name = "mdbook-rash"
path = "src/bin/mdbook-rash.rs"
doc = false

[dependencies]
rash_core = { path = "../rash_core", features = ["docs"] }
schemars = "0.8"
clap = "2"
chrono = "0.4"
env_logger = "0.9"
lazy_static = "1.4.0"
log = "0.4"
mdbook = { version = "0.4", default-features = false }
prettytable-rs = "^0.8"
regex = "1.5"
semver = "1.0"
serde_json = "1.0"
serde_yaml = "0.8"
