[package]
name = "mdbook_rash"
version = "0.1.0"
description = "Binary to create doc from `rash` code"
authors = ["Pando85 <pando855@gmail.com>"]
edition = "2018"
license-file = "../LICENSE"
homepage = "https://github.com/pando85/rash"
repository = "https://github.com/pando85/rash"
readme = "../README.md"

[[bin]]
name = "mdbook-rash"
path = "src/main.rs"
doc = false

[dependencies]
clap = "2"
chrono = "0.4"
env_logger = "0.6"
lazy_static = "1.4.0"
log = "0.4"
mdbook = { version = "0.3", default-features = false }
regex = "1.3.9"
semver = "0.10"
serde_json = "1.0"
