name: automerge
on:
  pull_request:
    types:
      - labeled
      - unlabeled
      - synchronize
      - opened
      - edited
      - ready_for_review
      - reopened
      - unlocked
  pull_request_review:
    types:
      - submitted
  check_suite:
    types:
      - completed
  status: {}
jobs:
  automerge:
    if: github.repository == 'rash-sh/rash'
    runs-on: ubuntu-latest
    steps:
      - name: automerge
        uses: "pascalgn/automerge-action@7ab42e888a333bf77ce865bc84fedc6a365a3548"
        env:
          GITHUB_TOKEN: "${{ secrets.PAT_GITHUB }}"
          # retry 60 times every 30s => 30min
          MERGE_RETRIES: 60
          MERGE_RETRY_SLEEP: 30000
          MERGE_METHOD: rebase
          MERGE_FORKS: false

