
name: github pages

on:
  push:
    branches:
      - master
    tags:
      - v*

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install stable toolchain
        id: toolchain
        uses: dtolnay/rust-toolchain@stable

      - run: rustup override set ${{steps.toolchain.outputs.name}}
      - run: rustup component add rustfmt

      - run: |
          cargo install mdbook --version 0.4.34

          GH_PAGES_DIR=./rash_book/rash-sh.github.io
          git clone --depth=1 https://github.com/rash-sh/rash-sh.github.io.git $GH_PAGES_DIR

          # Strip git ref prefix from version
          FULL_VERSION=$(echo "${{ github.ref }}" | sed -e 's,refs/tags/\(.*\),\1,')

          # Strip patch from version
          VERSION=$(echo "${FULL_VERSION}" | sed  's/^v\([0-9]\+\)\.\([0-9]\+\)\.[0-9]\+/v\1.\2/')

          VERSION=$VERSION make book

          # update _data/projects.json
          cd $GH_PAGES_DIR
          make _data/projects.json

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.PAT_GITHUB }}
          publish_dir: ./rash_book/rash-sh.github.io
          publish_branch: master
          external_repository: rash-sh/rash-sh.github.io
          enable_jekyll: true
