
name: github pages

on:
  push:
    branches:
      - master
    tags:
      - v*

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: rustfmt
          override: true

      - name: Setup mdBook
        uses: peaceiris/actions-mdbook@v1
        with:
          mdbook-version: '0.4.14'

      - run: |
          make mdbook-rash

          GH_PAGES_DIR=./rash_book/rash-sh.github.io
          git clone --depth=1 https://github.com/rash-sh/rash-sh.github.io.git $GH_PAGES_DIR

          # Strip git ref prefix from version
          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')

          VERSION=$VERSION make book

          # update _data/projects.json
          cd $GH_PAGES_DIR
          make _data/projects.json

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.PAT_GITHUB }}
          publish_dir: ./rash_book/rash-sh.github.io
          publish_branch: master
          external_repository: rash-sh/rash-sh.github.io
          enable_jekyll: true
